version: "3.2"

services:
  dev:
    container_name: tao
    image: parity/rust-builder:latest
    working_dir: /var/www/tao
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/tao/.cargo
    volumes:
      - .:/var/www/tao
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/tao --dev --ws-external"
